version: '3.3'

services:
  web:
    build: .
    command: gunicorn yourwakeel.wsgi:application --bind 0.0.0.0:8000
    expose:
      - 8000
    restart: always
    env_file:
      - ./.env
    volumes:
      - .:/home/app/web
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/documents
    depends_on:
      - postgres_db
      - qdrant_store

  nginx:
    build: ./nginx
    ports:
      - 8080:80
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/documents
    depends_on:
      - web

  postgres_db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

  qdrant_store:
    image: qdrant/qdrant:latest
    expose:
      - 6333
    volumes:
      - qdrant_data:/home/app/qdrant_data

volumes:
  postgres_data:
  static_volume:
  media_volume:
  qdrant_data:
